export enum ChannelExceptionCodes {
  CHANNEL_CREATION_FAILED = 'CHANNEL_CREATION_FAILED',
  CHANNEL_JOIN_FAILED = 'CHANNEL_JOIN_FAILED',
  CHANNEL_UPDATE_FAILED = 'CHANNEL_UPDATE_FAILED',
  CHANNEL_FETCH_FAILED = 'CHANNEL_FETCH_FAILED'
};